version: '3.8'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: statice-front
    tty: true
    ports:
      - 8081:8081  # TODO: 8081使って大丈夫？
    volumes:
      - ./front:/go/src